import Link from "next/link";

import Breadcrumb from "../../components/Breadcrumb";
import SideMenu from "../../components/SideMenu";

import layout from "../layout.module.scss";
import style from "./styles.module.scss";

const CSRCompanyListPage = () => {
  const data = [
    {
      spc_title: "台灣積體電路製造股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "上市",
      report_wy_start: 2007,
      report_new_year: 2022,
      link: "https://www.tsmc.com/chinese",
      vdr_book_link: "https://esg.tsmc.com/ch/resources/documents.html",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "聯華電子股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "上市",
      report_wy_start: 2008,
      report_new_year: 2022,
      link: "https://www.umc.com/zh-TW/Home/Index",
      vdr_book_link:
        "https://www.umc.com/zh-TW/Download/corporate_sustainability_reports",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "群創光電股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "上市",
      report_wy_start: 2010,
      report_new_year: 2022,
      link: "https://www.innolux.com/tw/index.html",
      vdr_book_link:
        "https://www.innolux.com/tw/esg/interaction/report_download.html",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "友達光電股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "上市",
      report_wy_start: 2010,
      report_new_year: 2022,
      link: "https://www.auo.com/zh-TW",
      vdr_book_link: "https://www.auo.com/zh-TW/csr/index",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "台灣康寧顯示玻璃股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "僑外資",
      report_wy_start: 2020,
      report_new_year: 2021,
      link: "https://www.corning.com/tw/zh_tw.html",
      vdr_book_link:
        "https://www.corning.com/tw/zh_tw/about-us/sustainability.html",
      vdr_book: "2021報告書",
      note: "",
    },
    {
      spc_title: "華邦電子股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "上市",
      report_wy_start: 2014,
      report_new_year: 2022,
      link: "https://www.winbond.com/hq/?__locale=zh_TW",
      vdr_book_link: "https://esg.winbond.com/resource/download",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "瀚宇彩晶股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "上市",
      report_wy_start: 2009,
      report_new_year: 2021,
      link: "https://www.hannstar.com/",
      vdr_book_link: "https://www.hannstar.com/tw/sustainability/report",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "能元科技股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "-",
      report_wy_start: "",
      report_new_year: 2022,
      link: "https://www.molicel.com/cn/tag/%E8%83%BD%E5%85%83%E7%A7%91%E6%8A%80/",
      vdr_book_link: "https://www.taiwancement.com/tw/esgReport.html",
      vdr_book: "2022報告書",
      note: "台泥集團發行",
    },
    {
      spc_title: "台達電子工業股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "上市",
      report_wy_start: 2005,
      report_new_year: 2022,
      link: "https://www.deltaww.com/zh-TW/index",
      vdr_book_link: "https://esg.deltaww.com/CSR-Reports",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "乾坤科技股份有限公司",
      spc_industry_type: "電腦週邊",
      spc_nature_type: "-",
      report_wy_start: "",
      report_new_year: 2022,
      link: "https://www.cyntec.com/",
      vdr_book_link: "https://esg.deltaww.com/CSR-Reports",
      vdr_book: "2022報告書",
      note: "台達電集團發行",
    },
    {
      spc_title: "晶元光電股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "-",
      report_wy_start: 2012,
      report_new_year: 2020,
      link: "https://www.epistar.com/EpistarTw/index",
      vdr_book_link: "https://www.epistar.com/EpistarTw/CsrDown",
      vdr_book: "2020報告書",
      note: "",
    },
    {
      spc_title: "三福氣體股份有限公司",
      spc_industry_type: "其他園區產業",
      spc_nature_type: "僑外資",
      report_wy_start: 2016,
      report_new_year: 2022,
      link: "https://www.airproducts.com.tw/",
      vdr_book_link: "https://www.sfchem.com.tw/zh-hant/page/10010461",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "精金科技股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "上市",
      report_wy_start: 2018,
      report_new_year: 2022,
      link: "https://www.hannstouch.com/tw",
      vdr_book_link: "https://www.hannstouch.com/tw/esg/download",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "台灣神隆股份有限公司",
      spc_industry_type: "生物科技",
      spc_nature_type: "上市",
      report_wy_start: 2013,
      report_new_year: 2021,
      link: "https://www.scinopharm.com.tw/index.asp",
      vdr_book_link: "https://www.scinopharm.com.tw/download.asp",
      vdr_book: "2021報告書",
      note: "",
    },
    {
      spc_title: "南茂科技股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "上市",
      report_wy_start: 2014,
      report_new_year: 2022,
      link: "https://www.chipmos.com/index.aspx",
      vdr_book_link: "https://www.chipmos.com/chinese/csr/report.aspx",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "聯詠科技股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "上市",
      report_wy_start: 2016,
      report_new_year: 2022,
      link: "https://www.novatek.com.tw/zh-TW/Home/Index",
      vdr_book_link: "https://esg.novatek.com.tw/zh-tw/download",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "智邦科技股份有限公司",
      spc_industry_type: "通訊產業",
      spc_nature_type: "上市",
      report_wy_start: 2016,
      report_new_year: 2022,
      link: "https://www.accton.com.tw/",
      vdr_book_link: "https://www.accton.com.tw/esg-documents/",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "瑞昱半導體股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "上市",
      report_wy_start: 2018,
      report_new_year: 2022,
      link: "https://www.realtek.com/zh-tw/",
      vdr_book_link: "https://www.realtek.com/zh-tw/csr/2021-10-08-09-58-30",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "華新科技股份有限公司",
      spc_industry_type: "通訊產業",
      spc_nature_type: "上市",
      report_wy_start: 2016,
      report_new_year: 2022,
      link: "https://www.passivecomponent.com/zh-hant/",
      vdr_book_link:
        "https://www.passivecomponent.com/zh-hant/csr/csr-reports/",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "亞旭電腦股份有限公司",
      spc_industry_type: "通訊產業",
      spc_nature_type: "-",
      report_wy_start: 2014,
      report_new_year: 2022,
      link: "https://www.askey.com.tw/tw/",
      vdr_book_link: "https://www.askey.com.tw/tw/csr/",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "住華科技股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "僑外資",
      report_wy_start: 2016,
      report_new_year: 2021,
      link: "https://www.sumika.com.tw/",
      vdr_book_link: "https://www.sumika.com.tw/society_data.htm",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "穩懋半導體股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "上櫃",
      report_wy_start: 2016,
      report_new_year: 2022,
      link: "https://www.winfoundry.com/zh-TW/",
      vdr_book_link: "https://www.winfoundry.com/wincsr/tw/downlaod.html",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "啓碁科技股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "上市",
      report_wy_start: 2011,
      report_new_year: 2022,
      link: "https://www.wnc.com.tw/",
      vdr_book_link: "https://csr.wnc.com.tw/zh/resources-and-downloads/",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "中強光電股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "上櫃",
      report_wy_start: 2008,
      report_new_year: 2022,
      link: "https://www.coretronic.com/",
      vdr_book_link: "https://www.coretronic.com/csr/report",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "茂迪股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "上櫃",
      report_wy_start: 2014,
      report_new_year: 2022,
      link: "http://www.motech.com.tw/",
      vdr_book_link: "https://www.motech.com.tw/download_center.php",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "東麗尖端薄膜股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "僑外資",
      report_wy_start: 2004,
      report_new_year: 2022,
      link: "https://www.toray.com.tw/tw/taiwan/network/tafk/",
      vdr_book_link: "https://www.toray.com/global/sustainability/download/",
      vdr_book: "2022報告書",
      note: "東麗集團發行",
    },
    {
      spc_title: "松瑞製藥股份有限公司",
      spc_industry_type: "生物科技",
      spc_nature_type: "上櫃",
      report_wy_start: 2022,
      report_new_year: 2022,
      link: "https://www.saviorlifetec.com.tw/zh/",
      vdr_book_link: "https://www.saviorlifetec.com.tw/zh/careers-200",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "采鈺科技股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "上市",
      report_wy_start: 2021,
      report_new_year: 2022,
      link: "https://www.viseratech.com/tw/about/",
      vdr_book_link: "https://esg.viseratech.com/",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "台康生技股有限公司橋頭分公司",
      spc_industry_type: "生物科技",
      spc_nature_type: "上櫃",
      report_wy_start: 2020,
      report_new_year: 2021,
      link: "https://zh-tw.eirgenix.com/",
      vdr_book_link: "https://zh-tw.eirgenix.com/esg-esg-overview",
      vdr_book: "2021報告書",
      note: "",
    },
    {
      spc_title: "東台精機股份有限公司",
      spc_industry_type: "精密機械",
      spc_nature_type: "上市",
      report_wy_start: 2018,
      report_new_year: 2022,
      link: "https://www.onation.com.tw/paper/other_select_index.php?id=2817&title_id=8004&group_id=608",
      vdr_book_link: "https://www.tongtai.com.tw/tw/csr.php",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "正達國際光電股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "上市",
      report_wy_start: 2022,
      report_new_year: 2022,
      link: "https://www.gtoc.com.tw/index.aspx",
      vdr_book_link: "https://www.gtoc.com.tw/webc/html/csr/06.aspx",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "台灣應用材料股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "-",
      report_wy_start: 2019,
      report_new_year: 2022,
      link: "https://www.appliedmaterials.com/tw/zh_tw.html",
      vdr_book_link:
        "https://www.appliedmaterials.com/tw/zh_tw/corporate-responsibility.html",
      vdr_book: "",
      note: "",
    },
    {
      spc_title: "帆宣系統科技股份有限公司",
      spc_industry_type: "精密機械",
      spc_nature_type: "上市",
      report_wy_start: 2013,
      report_new_year: 2022,
      link: "https://www.micb2b.com/",
      vdr_book_link: "https://www.micb2b.com/responsibility/report/",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "盟立自動化股份有限公司",
      spc_industry_type: "精密機械",
      spc_nature_type: "-",
      report_wy_start: 2021,
      report_new_year: 2021,
      link: "https://www.mirle.com.tw/",
      vdr_book_link: "https://www.mirle.com.tw/esg/document/",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "台灣穗高科技股份有限公司",
      spc_industry_type: "精密機械",
      spc_nature_type: "-",
      report_wy_start: 2017,
      report_new_year: 2021,
      link: "https://www.hodakatec.com/zh-tw",
      vdr_book_link: "https://www.hodakatec.com/zh-tw/promise_8.php",
      vdr_book: "2021報告書",
      note: "",
    },
    {
      spc_title: "崇越科技股份有限公司",
      spc_industry_type: "精密機械",
      spc_nature_type: "上市",
      report_wy_start: 2016,
      report_new_year: 2022,
      link: "https://www.topco-global.com/",
      vdr_book_link: "https://esg.topco-global.com/esg-resports/",
      vdr_book: "2021報告書",
      note: "",
    },
    {
      spc_title: "緯穎科技服務股份有限公司",
      spc_industry_type: "電腦週邊",
      spc_nature_type: "上市",
      report_wy_start: 2019,
      report_new_year: 2022,
      link: "https://www.wiwynn.com/",
      vdr_book_link: "https://www.wiwynn.com/zh/esg",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "東捷科技股份有限公司",
      spc_industry_type: "精密機械",
      spc_nature_type: "上櫃",
      report_wy_start: 2021,
      report_new_year: 2022,
      link: "https://www.contrel.com.tw/",
      vdr_book_link: "https://www.contrel.com.tw/inv_esg.php",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "希華晶體科技股份有限公司",
      spc_industry_type: "通訊產業",
      spc_nature_type: "上市",
      report_wy_start: 2020,
      report_new_year: 2022,
      link: "https://www.siward.com.tw/",
      vdr_book_link: "https://www.siward.com/tw/csr/sustainable-development",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "新揚科技股份有限公司",
      spc_industry_type: "電腦週邊",
      spc_nature_type: "僑外資",
      report_wy_start: 2014,
      report_new_year: 2014,
      link: "https://www.thinflex.com.tw/index.php",
      vdr_book_link:
        "https://www.thinflex.com.tw/archive/blame/csr/新揚初稿-20160202.pdf",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "國際日東科技股份有限公司",
      spc_industry_type: "精密機械",
      spc_nature_type: "-",
      report_wy_start: 2019,
      report_new_year: 2022,
      link: "",
      vdr_book_link: "https://www.nitto.com/tw/zht/sustainability/report/",
      vdr_book: "2014報告書",
      note: "日東電工株式會發行",
    },
    {
      spc_title: "川益科技股份有限公司",
      spc_industry_type: "精密機械",
      spc_nature_type: "-",
      report_wy_start: 2014,
      report_new_year: 2022,
      link: "https://www.kingslide.com/",
      vdr_book_link: "https://www.kingslide.com/csr_report",
      vdr_book: "2022報告書",
      note: "川湖科技發行",
    },
    {
      spc_title: "台灣賽孚思科技股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "僑外資",
      report_wy_start: 2003,
      report_new_year: 2022,
      link: "https://www.merckgroup.com/tw-zh",
      vdr_book_link:
        "https://www.merckgroup.com/en/sustainability-report/2022/services/downloads.html",
      vdr_book: "2022報告書",
      note: "默克集團發行",
    },
    {
      spc_title: "鈦昇科技股份有限公司",
      spc_industry_type: "精密機械",
      spc_nature_type: "上櫃",
      report_wy_start: 2015,
      report_new_year: 2015,
      link: "https://www.enr.com.tw/",
      vdr_book_link:
        "https://www.enr.com.tw/uploadfiles/628/投資/2015social-responsibility.pdf",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "台灣東喜璐機能膜股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "僑外資",
      report_wy_start: 2005,
      report_new_year: 2022,
      link: "https://www.mc-tohcello.co.jp/taiwan/",
      vdr_book_link:
        "https://jp.mitsuichemicals.com/jp/sustainability/others/report/index.htm",
      vdr_book: "2015報告書",
      note: "三井集團發行",
    },
    {
      spc_title: "聯亞光電工業股份有限公司",
      spc_industry_type: "通訊產業",
      spc_nature_type: "上櫃",
      report_wy_start: 2018,
      report_new_year: 2022,
      link: "https://www.lmoc.com.tw/index.php?lang=cht",
      vdr_book_link:
        "https://www.lmoc.com.tw/index.php?option=module&lang=cht&task=showlist&id=25&index=3",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "高力熱處理工業股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "僑外資",
      report_wy_start: 2021,
      report_new_year: 2022,
      link: "https://www.kaori.com.tw/tw/",
      vdr_book_link: "https://www.kaori.com.tw/tw/modules/about/esg",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "聯合骨科器材股份有限公司",
      spc_industry_type: "生物科技",
      spc_nature_type: "上櫃",
      report_wy_start: 2016,
      report_new_year: 2021,
      link: "https://www.unitedorthopedic.com/",
      vdr_book_link: "https://tw.unitedorthopedic.com/esg/report/",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "景岳生物科技股份有限公司",
      spc_industry_type: "生物科技",
      spc_nature_type: "上市",
      report_wy_start: 2014,
      report_new_year: 2014,
      link: "https://www.genmont.com.tw/product.htm",
      vdr_book_link: "",
      vdr_book: "2021報告書",
      note: "",
    },
    {
      spc_title: "家登精密工業股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "上櫃",
      report_wy_start: 2020,
      report_new_year: 2021,
      link: "https://esg.gudeng.com/",
      vdr_book_link: "https://www.gudeng.com/FileDownload?itemid=44&mid=348",
      vdr_book: "",
      note: "",
    },
    {
      spc_title: "萬潤科技股份有限公司",
      spc_industry_type: "精密機械",
      spc_nature_type: "上櫃",
      report_wy_start: 2013,
      report_new_year: 2021,
      link: "https://www.allring-tech.com.tw/",
      vdr_book_link:
        "https://www.allring-tech.com.tw/index.php?option=module&lang=cht&task=pageinfo&id=88&index=3",
      vdr_book: "2021報告書",
      note: "",
    },
    {
      spc_title: "上品綜合工業股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "上市",
      report_wy_start: 2021,
      report_new_year: 2022,
      link: "https://www.alliedsupreme.com/tw/",
      vdr_book_link: "https://www.alliedsupreme.com/tw/csr-116",
      vdr_book: "2021報告書",
      note: "",
    },
    {
      spc_title: "鑫科材料科技股份有限公司",
      spc_industry_type: "其他園區產業",
      spc_nature_type: "上櫃",
      report_wy_start: 2021,
      report_new_year: 2022,
      link: "https://www.e-ttmc.com.tw/chinese/index.html",
      vdr_book_link:
        "http://investor.e-ttmc.com.tw/index.php/zh_TW/frontend/index/node/14751175750001/node2/16328064450001",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "台灣力森諾科半導體材料股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "僑外資",
      report_wy_start: 2020,
      report_new_year: 2022,
      link: "https://www.resonac.com/jp",
      vdr_book_link:
        "https://www.resonac.com/jp/sustainability/report/report.html?intcid=glnavi_jp_sustainability_report_report",
      vdr_book: "2022報告書",
      note: "力森諾科株式會社發行",
    },
    {
      spc_title: "智崴資訊科技股份有限公司",
      spc_industry_type: "電腦週邊",
      spc_nature_type: "上櫃",
      report_wy_start: 2018,
      report_new_year: 2022,
      link: "https://www.brogent.com/zh-tw",
      vdr_book_link: "https://www.brogent.com/zh-tw/csr-report.html",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "閎康科技股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "上櫃",
      report_wy_start: 2020,
      report_new_year: 2022,
      link: "https://www.matek.com/zh-TW/home",
      vdr_book_link: "https://www.matek.com/zh-TW/Download/index/CSRReport",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "台灣田中電子股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "僑外資",
      report_wy_start: 2013,
      report_new_year: 2022,
      link: "https://www.tanaka.co.jp/english/",
      vdr_book_link: "https://www.tanaka.co.jp/english/about/csr/index.html",
      vdr_book: "2022報告書",
      note: "田中貴金屬集團發行",
    },
    {
      spc_title: "台灣日東光學股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "僑外資",
      report_wy_start: 2001,
      report_new_year: 2022,
      link: "https://www.nitto.com/tw/zht/",
      vdr_book_link: "https://www.nitto.com/tw/zht/sustainability/report/",
      vdr_book: "2022報告書",
      note: "日東電工株式會社發行",
    },
    {
      spc_title: "鈺登科技股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "-",
      report_wy_start: 2016,
      report_new_year: 2022,
      link: "https://www.edge-core.com/tw/",
      vdr_book_link: "https://www.accton.com.tw/esg-documents/",
      vdr_book: "2022報告書",
      note: "智邦集團發行",
    },
    {
      spc_title: "優貝克科技股份有限公司",
      spc_industry_type: "精密機械",
      spc_nature_type: "僑外資",
      report_wy_start: 2011,
      report_new_year: 2022,
      link: "https://www.ulvac.com.tw/",
      vdr_book_link:
        "https://www.ulvac.co.jp/en/sustainability/report/index.html",
      vdr_book: "2022報告書",
      note: "日本真空技術集團發行",
    },
    {
      spc_title: "世鎧精密股份有限公司",
      spc_industry_type: "精密機械",
      spc_nature_type: "上櫃",
      report_wy_start: 2021,
      report_new_year: 2021,
      link: "https://www.shehkai.com.tw/",
      vdr_book_link: "https://www.shehkai.com.tw/list/cate-60076.htm",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "汎銓科技股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "上市",
      report_wy_start: 2021,
      report_new_year: 2021,
      link: "https://www.msscorps.com/",
      vdr_book_link:
        "https://www.msscorps.com/ec99/rwd1520/category.asp?category_id=89",
      vdr_book: "2021報告書",
      note: "",
    },
    {
      spc_title: "金穎生物科技股份有限公司",
      spc_industry_type: "生物科技",
      spc_nature_type: "上櫃",
      report_wy_start: 2018,
      report_new_year: 2022,
      link: "https://www.geneferm.com/index.html",
      vdr_book_link: "https://www.geneferm.com/zh-tw/governance.html",
      vdr_book: "2021報告書",
      note: "",
    },
    {
      spc_title: "台灣明尼蘇達光電股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "-",
      report_wy_start: 2011,
      report_new_year: 2022,
      link: "https://www.3m.com.tw/3M/zh_TW/company-tw/",
      vdr_book_link: "https://www.3m.com.tw/3M/zh_TW/sustainability-tw/",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "統新光訊股份有限公司",
      spc_industry_type: "通訊產業",
      spc_nature_type: "上市",
      report_wy_start: 2012,
      report_new_year: 2021,
      link: "http://www.nextapogee.com.tw/ch/index.php",
      vdr_book_link: "http://www.nextapogee.com.tw/ch/csr.php",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "琳得科精密塗工股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "僑外資",
      report_wy_start: 2014,
      report_new_year: 2022,
      link: "https://www.lintec.com.tw/",
      vdr_book_link: "https://www.lintec.com.tw/csr?mode=csr",
      vdr_book: "2021報告書",
      note: "",
    },
    {
      spc_title: "儕陞生化技術股份有限公司",
      spc_industry_type: "生物科技",
      spc_nature_type: "僑外資",
      report_wy_start: 2012,
      report_new_year: 2012,
      link: "http://www.charsire.com.tw/",
      vdr_book_link: "",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "榮眾科技股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "僑外資",
      report_wy_start: 2020,
      report_new_year: 2022,
      link: "https://www.aresgreen.com.tw/",
      vdr_book_link: "http://frontken.com/sustainability/",
      vdr_book: "2014報告書",
      note: "Frontken集團發行",
    },
    {
      spc_title: "台灣荏原精密股份有限公司",
      spc_industry_type: "精密機械",
      spc_nature_type: "僑外資",
      report_wy_start: 2018,
      report_new_year: 2022,
      link: "https://www.ebara-tep.com.tw/index.html",
      vdr_book_link: "https://www.ebara.co.jp/en/ir/library/annual-report/",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "科林研發股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "僑外資",
      report_wy_start: 2019,
      report_new_year: 2022,
      link: "https://www.lamresearch.com/zh-hant/",
      vdr_book_link: "https://www.lamresearch.com/esg-report/",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "誠泰工業科技股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "上櫃",
      report_wy_start: 2018,
      report_new_year: 2021,
      link: "https://www.chetay.com.tw/index.php?lang=cht",
      vdr_book_link:
        "https://www.chetay.com.tw/index.php?option=module&lang=cht&task=showlist&id=443&index=1",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "台灣富士紡精密材料股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "僑外資",
      report_wy_start: 2021,
      report_new_year: 2022,
      link: "https://www.fujibo.co.jp/cn/index.html",
      vdr_book_link: "https://www.fujibo.co.jp/sustainability/report/",
      vdr_book: "2021報告書",
      note: "",
    },
    {
      spc_title: "濾能股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "上櫃",
      report_wy_start: 2021,
      report_new_year: 2021,
      link: "https://greenfiltec.com/",
      vdr_book_link: "https://greenfiltec.com/%e6%bf%be%e8%83%bdesg/",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "台灣捷恩智股份有限公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "僑外資",
      report_wy_start: 2009,
      report_new_year: 2022,
      link: "http://www.jnc-corp.com.tw/index_01.php",
      vdr_book_link: "https://www.jnc-corp.co.jp/sustainability/",
      vdr_book: "2021報告書",
      note: "JNC株式會社發行",
    },
    {
      spc_title: "台灣大福高科技設備股份有限公司",
      spc_industry_type: "精密機械",
      spc_nature_type: "僑外資",
      report_wy_start: 2002,
      report_new_year: 2022,
      link: "https://www.daifuku.com/",
      vdr_book_link: "https://www.daifuku.com/sustainability/report/",
      vdr_book: "2022報告書",
      note: "大福株式會社發行",
    },
    {
      spc_title: "東京威力科創股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "僑外資",
      report_wy_start: 2021,
      report_new_year: 2022,
      link: "https://www.tel.com/index.html",
      vdr_book_link: "https://www.tel.com/sustainability/report/index.html",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "中光電智能機器人股份有限公司",
      spc_industry_type: "精密機械",
      spc_nature_type: "-",
      report_wy_start: 2008,
      report_new_year: 2022,
      link: "https://www.coretronic-robotics.com/tw/index",
      vdr_book_link: "https://www.coretronic.com/csr/report",
      vdr_book: "2022報告書",
      note: "中強光電集團發行",
    },
    {
      spc_title: "鑫明材料股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "僑外資",
      report_wy_start: 2020,
      report_new_year: 2021,
      link: "https://www.entegris.com/",
      vdr_book_link:
        "https://www.entegris.com/en/home/about-us/corporate-social-responsibility.html",
      vdr_book: "2022報告書",
      note: "CMC Materials發行",
    },
    {
      spc_title: "博碩電業股份有限公司",
      spc_industry_type: "其他園區產業",
      spc_nature_type: "-",
      report_wy_start: 2013,
      report_new_year: 2022,
      link: "https://www.taya.com.tw/",
      vdr_book_link: "https://www.taya.com.tw/msg/msg292.html",
      vdr_book: "2021報告書",
      note: "大亞電線電纜集團發行",
    },
    {
      spc_title: "台灣富士電子材料股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "僑外資",
      report_wy_start: 2007,
      report_new_year: 2022,
      link: "https://holdings.fujifilm.com/en",
      vdr_book_link:
        "https://holdings.fujifilm.com/en/sustainability/report/2022",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "台灣華爾卡國際股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "僑外資",
      report_wy_start: 2012,
      report_new_year: 2022,
      link: "https://www.valqua.com.tw/",
      vdr_book_link:
        "https://www.valqua.co.jp/wp-content/uploads/2023/06/VALQUA-SR2023.pdf",
      vdr_book: "2022報告書",
      note: "華爾卡集團發行",
    },
    {
      spc_title: "台灣阿美特克股份有限公司",
      spc_industry_type: "精密機械",
      spc_nature_type: "僑外資",
      report_wy_start: 2019,
      report_new_year: 2021,
      link: "https://www.ametek.com.tw/",
      vdr_book_link: "https://www.ametek.com.tw/who-we-are/sustainability",
      vdr_book: "2022報告書",
      note: "",
    },
    {
      spc_title: "美商慧盛先進科技有限公司台灣分公司",
      spc_industry_type: "精密機械",
      spc_nature_type: "僑外資",
      report_wy_start: 2003,
      report_new_year: 2022,
      link: "https://www.merckgroup.com/tw-zh",
      vdr_book_link:
        "https://www.merckgroup.com/en/sustainability-report/2022/services/downloads.html",
      vdr_book: "2021報告書",
      note: "默克集團發行",
    },
    {
      spc_title: "新加坡商英特格股份有限公司",
      spc_industry_type: "積體電路",
      spc_nature_type: "僑外資",
      report_wy_start: 2020,
      report_new_year: 2021,
      link: "https://www.entegris.com/en/home.html",
      vdr_book_link:
        "https://www.entegris.com/en/home/about-us/corporate-social-responsibility.html",
      vdr_book: "2022報告書",
      note: "英特格集團發行",
    },
    {
      spc_title: "荷蘭商英特格國際控股有限公司台灣分公司",
      spc_industry_type: "光電產業",
      spc_nature_type: "僑外資",
      report_wy_start: 2020,
      report_new_year: 2021,
      link: "https://www.entegris.com/",
      vdr_book_link:
        "https://www.entegris.com/en/home/about-us/corporate-social-responsibility.html",
      vdr_book: "2021報告書",
      note: "英特格集團發行",
    },
  ];

  const menu_zh = [
    {
      title: "ESG專區",
      sub: [
        {
          title: "園區廠商專區",
          path: "/csr_company_list",
        },
        {
          title: "永續資料庫",
          path: "/sus_data",
        },
        {
          title: "ESG學習專區",
          sub: [
            {
              title: "如何撰寫報告書",
              path: "/report_writing",
            },
            {
              title: "GRI準則2021改版",
              path: "/gri",
            },
            {
              title: "公司治理3.0-永續發展藍圖",
              path: "/goverance3.0",
            },
            {
              title: "上市櫃公司永續發展行動方案",
              path: "/plan",
            },
          ],
        },
      ],
    },
  ];

  return (
    <div className={layout.page_layout}>
      <div className={layout.page_sidemenu}>
        <SideMenu />
      </div>
      <div className={layout.page_content}>
        <div className={layout.page_header}>
          <strong>園區廠商專區</strong>
          <Breadcrumb />
        </div>
        <div>
          <div className={layout.page_description}>
            <p>
              &nbsp;&nbsp;&nbsp;&nbsp;南科管理局積極輔導園區廠商推動永續發展、環保等相關的綠色制度，持續朝向綠色永續園區之目標邁進。至今園區內已有共{" "}
              {data.length}{" "}
              家事業單位發行永續報告書，展現園區事業社會責任經營成效。
              並推動廢棄物在地處理、園區植物殘枝落葉再利用、全面換置LED路燈等，成為全國第一座永續環境綠色園區，兌現環境保護及永續發展承諾。此外，持續推動園區從業勞工過勞預防與健康促進的工作，形塑科學園區安全、健康而永續的文化。以下為南科廠商推動企業社會責任報告書的資料。
            </p>
            <div>
              <div className={style.note_container}>
                <p>註:統計至2023年08月</p>
              </div>
              <table className={style.table_container} cellPadding={0}>
                <thead>
                  <tr>
                    <td>編號</td>
                    <td>產業別</td>
                    <td>公司名稱</td>
                    <td>性質</td>
                    <td>最新發行年度</td>
                    <td>撰寫起始年度</td>
                    <td>報告書連結</td>
                  </tr>
                </thead>
                <tbody>
                  {data.map((item, index) => (
                    <tr
                      key={item.spc_title}
                      className={
                        index % 2 !== 0 ? style.odd_row : style.even_row
                      }>
                      <td>{index + 1}</td>
                      <td>{item.spc_industry_type}</td>
                      <td>
                        <Link href={item.link || ""} target="_blank">
                          {item.spc_title}

                          {item.note && (
                            <>
                              <br /> ({item.note})
                            </>
                          )}
                        </Link>
                      </td>
                      <td>{item.spc_nature_type}</td>
                      <td>{item.report_new_year}</td>
                      <td>{item.report_wy_start}</td>
                      <td>
                        <Link
                          className={style.link}
                          style={
                            !item.vdr_book_link
                              ? {
                                  color: "gray",
                                  cursor: "not-allowed",
                                }
                              : {}
                          }
                          href={item.vdr_book_link || ""}
                          target="_blank">
                          檢視
                        </Link>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CSRCompanyListPage;
