#!/bin/sh
#/etc/rc.d/init.d/RPXSrv

# Source function library.
# chkconfig: 345 99 76
# description: Starts and Stops RPXSrv

stop() {
	echo "Shutting down RPXSrv"
	bash /etc/RPXEngine/srvstop.sh &
	return 0
}

start() {
	echo "Starting RPXSrv"
	bash /etc/RPXEngine/srvrunrhel6.sh &
	return 0
}

restart(){
	echo "Restarting RPXSrv"
	stop
	start
	return 0
}

case "$1" in
	start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
	*)
		echo "Usage: RPXSrv.service {start|stop}"
	exit 1
		;;
esac
exit $?
